
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: social_campus_flask
    depends_on:
      - mariadb
    ports:
      - "80:80"  
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: social_campus_nextjs
    ports:
      - "3000:3000"  
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next


  mariadb:
    image: mariadb:10.6.20
    container_name: social_campus_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: social_campus_v2
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  arangodb:
    image: arangodb:latest
    container_name: social_campus_arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=password
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3
    networks:
      - arango-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: social_campus_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"

volumes:
  mariadb_data:
  arango_data:

networks:
  arango-network:
    driver: bridge
